[package]
name = "moon_vcs2"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_common = { path = "../common" }
moon_process = { path = "../process" }
async-trait = { workspace = true }
ignore = "0.4.20"
miette = { workspace = true }
once_cell = { workspace = true }
once_map = "0.4.6"
regex = { workspace = true }
relative-path = { workspace = true }
rustc-hash = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
